const students = [{
    "id": 1,
    "first_name": "Sophi",
    "last_name": "O'Reilly",
    "email": "soreilly0@pbs.org"
  }, {
    "id": 2,
    "first_name": "Lorine",
    "last_name": "Werrett",
    "email": "lwerrett1@paginegialle.it"
  }, {
    "id": 3,
    "first_name": "Ethelyn",
    "last_name": "Snufflebottom",
    "email": "esnufflebottom2@digg.com"
  }, {
    "id": 4,
    "first_name": "Kellyann",
    "last_name": "Britton",
    "email": "kbritton3@abc.net.au"
  }, {
    "id": 5,
    "first_name": "Lulu",
    "last_name": "Pidon",
    "email": "lpidon4@php.net"
  }, {
    "id": 6,
    "first_name": "Felice",
    "last_name": "Garman",
    "email": "fgarman5@quantcast.com"
  }, {
    "id": 7,
    "first_name": "Zach",
    "last_name": "Harriskine",
    "email": "zharriskine6@usda.gov"
  }, {
    "id": 8,
    "first_name": "Sandie",
    "last_name": "Dunkerley",
    "email": "sdunkerley7@webeden.co.uk"
  }, {
    "id": 9,
    "first_name": "Kordula",
    "last_name": "Boddington",
    "email": "kboddington8@telegraph.co.uk"
  }, {
    "id": 10,
    "first_name": "Brook",
    "last_name": "Eckley",
    "email": "beckley9@wikipedia.org"
  }]
  module.exports = students